[package]
name = "rust_poc"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
once_cell = "1.0"
lazy_static = "1.4.0"

